# Generated by Django 5.1.3 on 2025-03-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='<function uuid4 at 0x0000020060A3AD40>', editable=False, max_length=36, unique=True),
        ),
    ]
