# Generated by Django 5.1.3 on 2025-06-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_chat_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatparticipant',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chatparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatParticipant',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
