# Generated by Django 5.1.3 on 2025-06-15 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fix_chat_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='app_chatmes_room_id_6ad6c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatroom',
            name='app_chatroo_is_acti_a2790c_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='chatparticipant',
            name='left_at',
        ),
        migrations.RemoveField(
            model_name='chatparticipant',
            name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='is_archived',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('system', 'System Message')], default='text', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_active'], name='app_chatroo_is_acti_67286a_idx'),
        ),
    ]
