# Generated by Django 5.1.3 on 2025-03-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='<function uuid4 at 0x000001EB64CC2B60>', editable=False, max_length=36, unique=True),
        ),
    ]
