# Generated by Django 5.1.3 on 2025-05-14 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['-CreatedDate']},
        ),
        migrations.AddField(
            model_name='domain',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='<function uuid4 at 0x000002032C095D00>', editable=False, max_length=36, unique=True),
        ),
    ]
