# Generated by Django 5.1.3 on 2025-05-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_room_room_id_chatroom_message_chatroommember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='<function uuid4 at 0x0000019F265A5D00>', editable=False, max_length=36, unique=True),
        ),
    ]
