# Generated by Django 5.1.3 on 2025-05-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_room_room_id_alter_session_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='<function uuid4 at 0x0000022359085D00>', editable=False, max_length=36, unique=True),
        ),
    ]
