# Generated by Django 5.1.3 on 2025-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='<function uuid4 at 0x000002221FF85D00>', editable=False, max_length=36, unique=True),
        ),
    ]
