# Generated by Django 5.1.3 on 2025-05-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_room_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='<function uuid4 at 0x0000017799545D00>', editable=False, max_length=36, unique=True),
        ),
    ]
