# Generated by Django 5.1.3 on 2025-05-29 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_session_booked_at_alter_room_room_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('TypeID', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=50)),
                ('TypeDescription', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='<function uuid4 at 0x00000283AE3C5D00>', editable=False, max_length=36, unique=True),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('ContentID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('File', models.FileField(blank=True, null=True, upload_to='content/')),
                ('URL', models.URLField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app.domain')),
                ('ContentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contenttype')),
            ],
            options={
                'ordering': ['-CreatedDate'],
            },
        ),
    ]
