# Generated by Django 5.1.3 on 2025-05-31 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_chatroom_options_chatroom_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='app_message_chat_ro_886dc3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='chatroommember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('ONE_TO_ONE', 'One-to-One'), ('SUPPORT_GROUP', 'Support Group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chatroom'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='<function uuid4 at 0x00000212F91B5D00>', editable=False, max_length=36, unique=True),
        ),
        migrations.RemoveField(
            model_name='chatroommember',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='chatroommember',
            name='is_active',
        ),
    ]
