# Generated by Django 5.1.3 on 2025-05-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientprofile_address_patientprofile_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='../photos/user_default_photo.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
